"""
Validation Utilities.
Provides strict validation for DataFrames, Prices, and Signal structures.
"""
import pandas as pd
import numpy as np
import math
from typing import Tuple, Dict, Any
from utils.helpers import safe_float


def validate_ohlcv_df(df: Any, min_bars: int = 20) -> bool:
    """
    Validate that the input is a proper OHLCV DataFrame with sufficient length.
    """
    if df is None or not isinstance(df, pd.DataFrame) or df.empty:
        return False
        
    if len(df) < min_bars:
        return False
        
    required_cols = ['open', 'high', 'low', 'close']
    for col in required_cols:
        if col not in df.columns:
            return False
            
    # Check for all-NaN columns which indicate corrupted data
    for col in required_cols:
        if df[col].isna().all():
            return False
            
    return True


def validate_trade_prices(entry: float, sl: float, tp: float, is_buy: bool, min_distance: float = 0.0) -> Tuple[bool, str]:
    """
    Strict validation for Trade Entry, Stop Loss, and Take Profit prices.
    
    Returns:
        Tuple of (is_valid: bool, reason: str)
    """
    entry = safe_float(entry)
    sl = safe_float(sl)
    tp = safe_float(tp)
    
    # 1. Zero / Negative Price Check
    if entry <= 0 or sl <= 0 or tp <= 0:
        return False, "Prices must be strictly positive (> 0)"
        
    # 2. NaN Check
    if math.isnan(entry) or math.isnan(sl) or math.isnan(tp):
        return False, "Prices contain NaN values"
        
    # 3. Directional Logic Check
    if is_buy:
        if sl >= entry:
            return False, "BUY SL must be strictly less than Entry"
        if tp <= entry:
            return False, "BUY TP must be strictly greater than Entry"
    else:
        if sl <= entry:
            return False, "SELL SL must be strictly greater than Entry"
        if tp >= entry:
            return False, "SELL TP must be strictly less than Entry"
            
    # 4. Minimum Distance Check (Prevents MT5 TRADE_RETCODE_INVALID_STOPS)
    if min_distance > 0:
        sl_dist = abs(entry - sl)
        tp_dist = abs(tp - entry)
        if sl_dist < min_distance:
            return False, f"SL distance ({sl_dist:.2f}) < min_distance ({min_distance:.2f})"
        if tp_dist < min_distance:
            return False, f"TP distance ({tp_dist:.2f}) < min_distance ({min_distance:.2f})"
            
    return True, "Valid"


def validate_signal_structure(signal: Dict[str, Any]) -> Tuple[bool, str]:
    """
    Validate the structural integrity of a signal dictionary generated by a Strategy.
    """
    if not isinstance(signal, dict):
        return False, "Signal is not a dictionary"
        
    if 'signal' not in signal:
        return False, "Missing 'signal' key"
        
    if signal['signal'] == 'NEUTRAL':
        return True, "Neutral signal"
        
    if 'meta' not in signal or not isinstance(signal['meta'], dict):
        return False, "Missing or invalid 'meta' dictionary"
        
    meta = signal['meta']
    required_meta_keys = ['strategy', 'entry_price', 'sl_price', 'tp_price', 'timeframe']
    for key in required_meta_keys:
        if key not in meta:
            return False, f"Missing required meta key: {key}"
            
    # Validate prices inside meta
    is_buy = 'BUY' in signal['signal'].upper()
    is_valid, reason = validate_trade_prices(
        meta['entry_price'], meta['sl_price'], meta['tp_price'], is_buy
    )
    
    if not is_valid:
        return False, f"Invalid prices in meta: {reason}"
        
    return True, "Valid"